          - label: "Dokumentit"
            name: "documents"
            widget: "list"
            fields:
              - { label: "Nimi", name: "title", widget: "string" }
              - { label: "PDF", name: "url", widget: "file", media_library: { allow_multiple: false } }

          - label: "Galleria"
            name: "gallery"
            widget: "list"
            fields:
              - { label: "Otsikko", name: "title", widget: "string" }
              - { label: "Kaupunki", name: "city", widget: "string", required: false }
              - { label: "Kuva", name: "image", widget: "image" }
              - { label: "Kuvaus", name: "text", widget: "text", required: false }
